# Generated by Django 5.2.6 on 2025-09-22 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='neme',
            new_name='name',
        ),
    ]
