# Generated by Django 5.2.6 on 2025-09-25 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_neme_article_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date']},
        ),
    ]
