# Generated by Django 5.2.6 on 2025-09-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_article_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='category',
            new_name='post_category',
        ),
    ]
